### PR TITLE
Add Project.toml, delete REQUIRE

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by richardreeve** [comment]
This is already in #20, so I'm not going to merge this unless I can't fix the few remaining issues there...

**Comment by mkborregaard** [comment]
Oh you get a segfault? Or is the "precompilation is broken" thing?

**Comment by mkborregaard** [comment]
And is it only on 1.0 or also on later julias?

**Comment by asinghvi17** [comment]
Fair enough!  I just needed a branch to base off of for CI.

**Comment by mkborregaard** [comment]
@richardreeve the back story is that we (Anshul) is currently making it possible for Makie to plot the plot recipes for phylogenies here too.

**Comment by richardreeve** [comment]
The precompilation thing is annoying, but seems to be coming from `SimpleTraits`. It's at least one actual bug rather than segfaulting. I'm working on it now.

**Comment by richardreeve** [comment]
Ah, okay. Hopefully it's something really stupid and it'll be fixed later today (and nothing else will crop up). If I can't get `rr/linkedlist` merged tomorrow, I'll go with this as a temporary fix though, unless you really need it today?

**Comment by asinghvi17** [comment]
Nope, nothing urgent on this - I'm just adding my fork during testing for now.  It can wait for a week or so...eventually I do want to register the package which uses this, though.

**Comment by richardreeve** [comment]
Sure, of course. I'll get it done as soon as I can.

**Comment by richardreeve** [comment]
Now fixed in v0.4.0.

**Pull request closed without merging**
