### PR TITLE
Really fix dependencies

### PR DESCRIPTION
**Pull request by mkborregaard**
This reverts commit f361f786a0c048c9ab9be41ab7b42a822eca8e41.

### CODE REVIEW

**Comment by mkborregaard** [comment]
Hello @richardreeve the fix on PenaltyFunctions appears to have fixed the issues - I've removed the two unnecessary deps again and widened the compat on RecipesBase. This is ready to merge.

**Comment by richardreeve** [comment]
Thanks so much for this @mkborregaard. I’m slightly relieved you didn’t find it trivial after I was tearing my hair out over it, but mostly just pleased it’s fixed! Why anyone thinks it’s good practice to have travis see different dependencies that people’s machines is a mystery that may never get resolved!

**Comment by mkborregaard** [comment]
I think other people installing your package with `add` would have the same problem

**Comment by richardreeve** [comment]
Okay. I didn’t get the same result when I freed Phylo to get to the default package on General, but I guess I couldn’t free Diversity because I couldn’t get it to pass travis and so release a version.

**Comment by mkborregaard** [comment]
it's a bit weird

**Pull request merged**
