### PR TITLE
fix plotting heights; close #19

### LINKED ISSUE #19: Fan plots look wrong
Not sure what's going on here, but fan plots are not working correctly, even though dendrogram plots work fine. I can't see an obvious difference between the two recipes, but there's obviously something in there...

### PR DESCRIPTION
**Pull request by mkborregaard**
I also fixed the `sort!` method for the impl - please have a look. 
sort! has neither docs nor tests here - where and how should I add?

### CODE REVIEW

**Comment by mkborregaard** [comment]
Note that this PR is to the linkedlist branch.
Also
Before:
Screenshot 2019-11-09 at 10 00 51
After:
Screenshot 2019-11-09 at 10 00 10

**Comment by richardreeve** [comment]
If you can merge in `rr/linkedlist` again, then hopefully all of the tests should now work. As far as `sort!` is concerned, obviously putting in docs and tests would be great. Since `sort!` is currently in `src/plot.jl`, then you can just put the docs in there, and the test in `test/test_plot.jl`. It'll automatically get picked up by the test framework. If you want to put an example of using it more generally into the main README, that would be great if you think it's generally useful... maybe if so we could think about moving it out of the plot file later, but there's no rush.

**Comment by mkborregaard** [comment]
OK, I've rebased unto master.
You have two plots in your new readme, right? That's where it could be added - just before plotting, it will make the plot look nicer. Might I suggest you make one of those plots a fan plot too, to show off that functionality?

**Comment by mkborregaard** [comment]
I added a docstring too for `sort!`

**Comment by mkborregaard** [comment]
OK, added sort! to readme too, and made that one a fanplot. Should we not have the actual plots in the readme too, then?

**Comment by richardreeve** [comment]
Please do if you have time! I've just never got around to it...

**Comment by mkborregaard** [comment]
OK, I've added plots. It doesn't look super nice with the default values and there's some overlap - would be nice to have one of the plots from the plotting PR in there instead.
Also - I've changed the plotting traversals to `preorder` from `postorder`, pretty sure that's correct

**Comment by mkborregaard** [comment]
Perhaps the two examples from hummingbirds here https://github.com/richardreeve/Phylo.jl/pull/15 just with your new trait evolution model?

**Comment by mkborregaard** [comment]
I've factored out the readme edits and some other things I'd like to do, so this can be merged in it's current form. Travis is green.

**Pull request merged**
