### PR TITLE
plotting of AbstractTrees; close #8

### LINKED ISSUE #8: Plotting topology and big trees
Hi,
This is another feature that would be really useful. Plotting perhaps using plotly backend, so big trees can be viewed and zoom-ed in/out. I see there is show() function, but it does not show topology.
Being able to display tree, branches, how they are arranged, to immediately see the whole tree, just right away from the Julia code, is really nice for diagnostics. Maybe such function already exists ?

### PR DESCRIPTION
**Pull request by mkborregaard**
### Do not merge yet

This PR awaits some improvements on the text formatting side in Plots, which may be a little while. However, I just wanted to show the progress and ideas, and harvest feedback. Feedback on anything - the interface, commands, defaults, line widths, font sizes, spacing etc very welcome. This is a crucial part of getting it right.

I've put some general considerations in #14, as there was things that was difficult for me to learn and adapt to.

The PR adds plotting functionality for AbstractTrees. I've essentially ignored the whole concept of branches (I think of them as property of their subtending nodes) and done everything on nodes. Everything is designed to fit in with the existing syntax of Plots.

One improvement I still want to do is to allow passing things like `line_z` (to color the lines) as `Dict{Node, T}` and have the recipe transform it into Vectors, so the user will  not have to worry about ordering things the right way.

I've also made a `ladderize` function for better plotting to throw in, but I can't get the thing to work. I think it's something to do with the traversal order.

```julia
# Read the tree and load the plotting ocde
using Phylo
using Plots
include("/Users/michael/.julia/dev/Phylo/src/plot.jl")
gr(fmt = :png, lc = :black)
```

There are two basic layouts:
`:dendrogram` (the default)
```julia
passerines = open(t->parsenewick(t, NamedPolytomousTree), "delete/passerines.tree")
plot(passerines, size = (400, 1200), showtips = false)
```
skaermbillede 2018-09-11 kl 14 35 28

and `:fan`

```julia
hummers = open(t->parsenewick(t, NamedPolytomousTree), "delete/hummingbirds.tree")
plot(hummers, treetype = :fan)
```
skaermbillede 2018-09-11 kl 14 48 39

You can color the branches after a variable. So let us evolve a trait on the
hummingbird tree according to Brownian motion. I use a depth-first recursive mapping
function I've also put in the code
```julia
evolve(tree) = map_depthfirst((val, node) -> val + randn(), 0., tree, Float64)
trait = evolve(hummers)
plot(hummers, treetype = :fan, line_z = trait, lw = 5, showtips = false, c = :RdYlBu)
```
skaermbillede 2018-09-11 kl 14 51 48

Or let's highlight the oscines in the passerine tree
```julia
osc_color = map_depthfirst((val, node) -> node == "Oscines" ? :orange : val, :black, passerines)
plot(passerines, linecolor = osc_color, showtips = false, lw = 2, size = (400, 1200))
```
skaermbillede 2018-09-11 kl 15 17 13

It's also got support for markers (that can have different colors and layout as well), and basic support for branch annotations (though this isn't as nice as it should be).
```julia
plot(hummers, lc = :orange, lw = 5, size = (400, 1100), markersize = 4, series_annotations = text.(1:count(!isleaf, nodeiter(tree)), 6, :right, :bottom), msc = :white)
```
skaermbillede 2018-09-11 kl 15 10 02

Finally, it's already somewhat efficient (but there is plenty of room for avoiding allocations and making it faster still)

```julia
qian = open(t->parsenewick(t, NamedPolytomousTree), "delete/Qian2016.tree") # this takes several minutes
# PolytomousTree{DataFrames.DataFrame,Dict{String,Any}} with 31389 tips, 62776 nodes and 62775 branches.
# Leaf names are Blasia_pusilla, Lunularia_cruciata, Marchantia_polymorpha, Riccia_fluitans, Reboulia_hemisphaerica, ... [31383 omitted] ... and Salvia_aethiopis

@time display(plot(qian, showtips = false, treetype = :fan))
# 1.012017 seconds (3.81 M allocations: 169.401 MiB, 25.17% gc time)
```
skaermbillede 2018-09-11 kl 15 05 20

### CODE REVIEW

**Comment by mkborregaard** [comment]
I'll write tests before merging of course.

**Comment by richardreeve** [comment]
It all looks great so far - I'll have a look in more detail tomorrow. In the meanwhile, if you want an easily accessible tree that you don't have to delete to work with for plotting that we can play with too, then in the repo `test/H1N1.trees` has two copies of the flu tree in a nexus file with a lot of metadata in it:
```julia
julia> tree = open(parsenexus, "test/H1N1.trees")["TREE1"]
[ Info: Created a tree called 'TREE1'
[ Info: Created a tree called 'TREE2'
BinaryTree{DataFrames.DataFrame,Dict{String,Any}} with 507 tips, 1013 nodes and 1012 branches.
Leaf names are H1N1_A_MIYAGI_3_2000, H1N1_A_PARMA_6_2008, H1N1_A_AKITA_86_2002, H1N1_A_DAKAR_14_1997, H1N1_A_EGYPT_84_2001, ... [501 omitted] ... and H1N1_A_HONGKONG_2070_1999

julia> getnoderecord(tree, "H1N1_A_PARMA_6_2008")
Dict{String,Any} with 12 entries:
  "rate_95%_HPD"   => [0.000800258, 0.00565223]
  "length_median"  => 1.0634
  "rate"           => 0.00295453
  "length_range"   => [0.272117, 2.10698]
  "height_range"   => [1.0, 1.0]
  "length"         => 1.06811
  "height"         => 1.0
  "rate_median"    => 0.00270733
  "rate_range"     => [0.00036974, 0.0152626]
  "length_95%_HPD" => [0.629248, 1.47885]
  "height_95%_HPD" => [1.0, 1.0]
  "height_median"  => 1.0
```

**Comment by mkborregaard** [comment]
I've added the fix to Plots in v0.22.2 (tagged) and updated this, so now this works and can be merged.

**Comment by richardreeve** [comment]
I've merged this, but I haven't put out a release yet, because I have finally fixed the problem I had with Julia 1.0 crashing. If I don't manage to get everything working by the end of today I'll release this as is, but I'm hoping to at least revise the whole API and Interface so that all future changes will be fairly seamless...

**Comment by richardreeve** [comment]
Yeah, well... time will tell!

**Pull request merged**
